### ISSUE TITLE
Running into 'class not registered' error when running the sample

### ISSUE THREAD

**Issue by Praburaj** [AzureAD/azure-activedirectory-library-for-cordova#10]
I followed the instructions at https://github.com/AzureAD/azure-activedirectory-library-for-cordova and tried to run the sample https://github.com/AzureAD/azure-activedirectory-library-for-cordova/tree/master/sample. However in the UI I always run into this: 

![image](https://cloud.githubusercontent.com/assets/2294732/7973572/f8bd26f4-0a0b-11e5-8ede-39e8a90a0824.png)

On debugging this a little further I am noticing the following exception at this line: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/windows/ADALProxy.js#L65

```
WinRTError: Class not registered
at ADALProxy.createAsync (ms-appx://io.cordova.hellocordova/www/plugins/cordova-plugin-ms-adal/src/windows/ADALProxy.js:65:17)\n   at module.exports (ms-appx://io.cordova.hellocordova/www/cordova.js:874:13)\n   at cordovaBridge.executeNativeMethod (ms-appx://io.cordova.hellocordova/www/plugins/cordova-plugin-ms-adal/www/CordovaBridge.js:41:9)\n   at AuthenticationContext.createAsync (ms-appx://io.cordova.hellocordova/www/plugins/cordova-plugin-ms-adal/www/AuthenticationContext.js:57:5)\n   at app.createContext (ms-appx://io.cordova.hellocordova/www/js/index.js:81:9)"
```

I'm very much blocked on this issue. Will totally appreciate if you could give any pointers.

**Comment by sgrebnov** [comment]
Looks like to be an msbuild14 issue. @Praburaj - do you use VS 2013? If so, please try installing [Update 5](https://www.visualstudio.com/news/vs2013-update5-vs).

**Comment by sgrebnov** [comment]
To verify this, please see if  you have the following elements in AppManifest.xml generated by the build process

```
<ActivatableClass ActivatableClassId="Microsoft.IdentityModel.Clients.ActiveDirectory.UserIdentifier" ThreadingModel="both" />
<ActivatableClass ActivatableClassId="Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" ThreadingModel="both" />
```

**Comment by Praburaj** [comment]
Thanks @sgrebnov That indeed fixed the problem.

**Comment by sgrebnov** [comment]
Great, closing this issue...
