### ISSUE TITLE
Error Deploying Plugin in Oracle MAF

### ISSUE THREAD

**Issue by SoonersBaby** [AzureAD/azure-activedirectory-library-for-cordova#150]
### Issue Description
After successfully importing the latest ADAL Cordova plugin in Oracle Mobile application Framework (MAF) via (JDeveloper) I'm getting the following error when deploying to my android device.  Other third party plugins deploy fine. I've made no changes to the plugin prior to import or deployment.

[02:46:16 PM] Installing "cordova-plugin-ms-adal" for android
[02:46:16 PM] Error Code : INTERNAL_ERROR
[02:46:16 PM] Cannot call method 'indexOf' of undefined
[02:46:16 PM] oracle.maf.mafhelper.api.MafHelperException: oracle.maf.mafhelper.api.MafHelperException: java.lang.Exception
[02:46:16 PM] at oracle.maf.mafhelper.internal.utils.MafHelperInternalUtilities.runProcess(Unknown Source)
[02:46:16 PM] at oracle.maf.mafhelper.internal.utils.MafHelperInternalUtilities.executeCmd(Unknown Source)
[02:46:16 PM] at oracle.maf.mafhelper.internal.utils.MafHelperInternalUtilities.addPlugin(Unknown Source)
[02:46:16 PM] at oracle.maf.mafhelper.internal.utils.MafHelperInternalUtilities.deploy(Unknown Source)
[02:46:16 PM] at oracle.maf.mafhelper.MafHelperMain.main(Unknown Source)
[02:46:16 PM] Caused by: oracle.maf.mafhelper.api.MafHelperException: java.lang.Exception
[02:46:16 PM] ... 5 more
[02:46:16 PM] Caused by: java.lang.Exception
[02:46:16 PM] at oracle.maf.mafhelper.api.MafHelperException.<init>(Unknown Source)
[02:46:16 PM] ... 5 more
[02:46:16 PM] Deployment cancelled.
[02:46:16 PM] ----  Deployment incomplete  ----.
[02:46:16 PM] An error occurred deploying Cordova plugins. (oracle.adfmf.framework.dt.deploy.android.deployers.plugins.AndroidPluginDeployer)

### Repro Environment Details
1. Installed latest plugin version:  v0.9.0

2. Target Platform: Android

3. Test device and OS version:  Samsung S7 and Android Emulator

4. Are you using Cordova from command line or special Cordova IDE: Cordova version bundled with Oracle MAF (JDeveloper)

3. If Windows related, please specify whether SSO option is enabled or not. MAC

**Comment by matrosov-nikita** [comment]
@SoonersBaby, thanks for reporting. Are you able to install another cordova plugin and check whether MAF throws the same error when deploying?

**Comment by SoonersBaby** [comment]
Yes, I installed the cordova-plugin-vibration and it installed fine. 

Also, I get the same errors deploying to Android emulator. However, when I deploy to an iOS emulator I only get the single error below, and it continues to deploy.

[03:09:05 PM] Cannot call method 'indexOf' of undefined

Thanks.

**Comment by matrosov-nikita** [comment]
@SoonersBaby, thanks for the information, did you try this [solution](http://stackoverflow.com/a/36619718/4934330)?

**Comment by matrosov-nikita** [comment]
@SoonersBaby, also I've set up an environment on the windows machine and tried to reproduce this issue w/o success. 
There are logs:
```
[01:33:59 PM] Validating run configuration...
[01:33:59 PM] Deploying application...
[01:33:59 PM] ----  Deployment started.  ----
[01:33:59 PM] Target platform is  (Android).
[01:33:59 PM] Beginning deployment of MAF application "Application1" to Android device using profile "Android1".
[01:33:59 PM] Capturing state changes of MAF application source files in application scope for just-in-time "Clean All" analysis.
[01:33:59 PM] A prior deployed config.json file does not exist for the current deployment profile. A new config.json file must be created.
[01:33:59 PM] The need to generate a new config.json file means that deployment content is invalid and requires a just-in-time "Clean All" on the MAF application to ensure a good deployment.
[01:33:59 PM] Performing just-in-time "Clean All" on MAF application build and deployment content to ensure a good deployment.
[01:33:59 PM] Checking state of Android Debug Bridge server...
[01:33:59 PM] Android Debug Bridge server already running.
[01:34:03 PM] Verifying a single Android device is online and connected to the ADB server...
[01:34:03 PM] Deleting some previously deployed content.
[01:34:03 PM] Creating file config.json
[01:34:03 PM] Creating debug key store...
[01:34:04 PM] Running dependency analysis...
[01:34:04 PM] Building...
[01:34:04 PM] Deploying 3 profiles...
[01:34:04 PM] Verifying project is a MAF project...
[01:34:04 PM] Wrote Archive Module to C:\JDeveloper\mywork\Application1\ViewController\deploy\ViewController_MobileFeatureArchive1.jar
[01:34:05 PM] Verifying project is a MAF project...
[01:34:05 PM] Wrote Archive Module to C:\JDeveloper\mywork\Application1\ApplicationController\deploy\ApplicationController_MobileFeatureArchive1.jar
[01:34:05 PM] Copying FARs to the MAF application...
[01:34:05 PM] Extracting Feature Archive file, "ApplicationController_MobileFeatureArchive1.jar" to deployment folder, "ApplicationController".
[01:34:05 PM] Extracting Feature Archive file, "ViewController_MobileFeatureArchive1.jar" to deployment folder, "ViewController".
[01:34:05 PM] Copying .adf files...
[01:34:05 PM] Copying adfmf-manifest.properties file...
[01:34:05 PM] Copying application image files...
[01:34:05 PM] Creating Android preferences XML files...
[01:34:05 PM] Creating the Android template...
[01:34:05 PM] Command-line executed:  "C:\Program Files\Java\jdk1.8.0_112\bin\java" -jar "D:\Oracle\Middleware\Oracle_Home\jdeveloper\jdev\extensions\oracle.maf\maf-helper.jar" createTemplate -config "C:\JDeveloper\mywork\Application1\deploy\Android1\config.json"
[01:34:08 PM] Installing "maf-cordova-plugin-network-access" for android
[01:34:09 PM] Installing "cordova-plugin-ms-adal" for android
[01:34:10 PM] Fetching plugin "cordova-plugin-compat" via npm
[01:34:10 PM] Installing "cordova-plugin-compat" for android
[01:34:31 PM] Copying security related files to the MAF application...
[01:34:31 PM] Creating the Android application...
[01:34:31 PM] Command-line executed from path: /C:/JDeveloper/mywork/Application1/deploy/Android1/android_template/
[01:34:31 PM] Command-line executed:  "C:\JDeveloper\mywork\Application1\deploy\Android1\android_template\gradlew.bat" assembleRelease -Pmaf_secure_props=maf_key_store_password,maf_key_password
[01:34:32 PM] Compiling Cordova plugin gradle library 'com.microsoft.aad:adal:1.10.0'
[01:34:32 PM] Observed package id 'add-ons;addon-unknown-unknown-19' in inconsistent location 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-google_apis-google-19' (Expected 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-unknown-unknown-19')
[01:34:33 PM] The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
[01:34:33 PM] Incremental java compilation is an incubating feature.
[01:34:33 PM] The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
```

**Comment by SoonersBaby** [comment]
@matrosov-nikita, interesting that you got no errors. I'm using JDeveloper 12.1.3.0  with MAF version 2.2.1 (required for compatibility for some delivered Oracle apps of the same MAF level). Also, my maf-application.xml has no "Cordova Engine Version" option.

However, as [this link](https://docs.oracle.com/middleware/maf221/mobile/install/GUID-91DF0B93-265C-408B-8128-F0F3A1D91EC2.htm#MAFIG24925) indicates, MAF 2.2.1 uses the Cordova versions below.

> MAF applications in 2.2.1 use Cordova 3.7.2 on Android and Cordova 3.8.0 on iOS.

I'll see about upgrading to a later MAF version and see if it works.

Thanks,
Blake

**Comment by matrosov-nikita** [comment]
@SoonersBaby, I'm using JDeveloper v.12.2.1 and MAF v.2.4.0. 
Did you have a chance to upgrade your environment?

**Comment by SoonersBaby** [comment]
@matrosov-nikita

Yes, sorry about the late reply. I had to upgrade several components including my MAC O/S in order to get all the later versions of JDeveloper/MAF/XCode installed.  I've completed that and installed the plugins again but now I'm getting the error below about the Cordova version not being high enough.

![image](https://cloud.githubusercontent.com/assets/22177898/26005111/0c7c2ee6-3706-11e7-8b59-a7ca4a46741c.png)

I'm not sure what version of MAF you installed, but I have to install 2.3.3.0 since that is the most recent version that Oracle delivers in the pre-built mobile apps for our product (JD Edwards).  That MAF version uses the following Cordova versions. 

![image](https://cloud.githubusercontent.com/assets/22177898/26004946/7eb38410-3705-11e7-8562-ae1b5c7fa069.png)

Any chance to get a working ADAL plugin compatible with that Cordova version?

Thanks

**Comment by matrosov-nikita** [comment]
@SoonersBaby, thanks for trying, it seems to me that `MAF` 2.3.3.0 contains bundled cordova@4.x which doesn't satisfy [requirements](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/package.json#L28) for `cordova-plugin-ms-adal` plugin.  You need to get [MAF v.2.4.0](http://www.oracle.com/technetwork/developer-tools/maf/documentation/maf240relnotes-3630024.html) (was released in April, 2017), where cordova engine versions have been updated. According to this [docs](http://www.oracle.com/technetwork/developer-tools/maf/documentation/mafarchive-2352433.html), you will have to install `JDeveloper v12.2.1`.

**Comment by SoonersBaby** [comment]
@matrosov-nikita,

After updating to `MAF 2.4.0`, I was able to deploy the `cordova-plugin-ms-adal` plugin.  Thanks for the assistance.
